### ISSUE TITLE
Statement action unable to validate true/false

### ISSUE THREAD

**Issue by J0rdyV** [induxx/parsable-file-multi-tool#31]
When using a statement action to validate a boolean in Akeneo (over API),
The value that is set, is (boolean)True or (boolean)False.
But you are unable to validate because the statement action `EQUALS true` forces the true to be a string.

Example code that does not work
```
    status:
      action: statement
      when:
        field: Active
        operator: EQUALS
        state: true
      then:
        field: Status
        state: 'OK'
```

See `src/Component/Statement/EqualsStatement.php` line 16.
